#documentation: https://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - osx
  - linux
  - windows

julia:
  - 1.5
  - nightly

notifications:
  email: false

git:
  depth: 99999999

before_script: # install dependent unregistered packages
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.add([PackageSpec(url="https://github.com/OpenMendel/SnpArrays.jl.git")]);'

after_script: # test package, use wait time 20 min
  - travis_wait 20 julia -e 'using Pkg, MendelIHT; cd(joinpath(dirname(pathof(MendelIHT)), "..")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(process_folder())'

jobs:
  allow_failures:
    - os: osx # tests can take >50 min on osx which causes travis to time out
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.5
      os: osx
      script:
        - julia -e 'using Pkg; Pkg.add("Documenter")'
        - julia -e 'using MendelIHT; include(joinpath(dirname(pathof(MendelIHT)), "..", "docs", "make.jl"))'
      after_script: skip
      after_success: skip
